### PR TITLE
JPERF-741: Improve GHA Configuration

### PR DESCRIPTION
**Pull request by mzyromski-atlassian**
- Introduce multiple jobs with different Jira versions 
- Remove old, unused TravisCI configuration
- Replace README CI badge

Example build: https://github.com/mzyromski-atlassian/jira-actions/actions/runs/795128925
image

### CODE REVIEW

**Review by dagguh — DISMISSED** [review]
The screenshot is a thing of beauty ❤️

**Comment by mzyromski-atlassian** [comment]
OK, so the PR is not mergeable, although the CI was green. It might have been caused by the fact that I force-pushed changes right after I pushed the original branch which resulted in two workflow executions being run. I'll try rerunning the CI and see if it helps.

**Review by dagguh — DISMISSED** [review]

**Comment by mzyromski-atlassian** [comment]
Turns out, with a matrix of jobs, one needs to explicitly specify all of them as required checks in GH repo configuration. @dagguh has an interesting idea on how to work around this, which I will give a shot, most likely tomorrow.

**Comment by mzyromski-atlassian** [comment]
I modified the workflow so that on top of `build` jobs matrix there's also `build-check` job that depends on all the regular jobs and is now selected as a merge check. 
image

**Review by dagguh — APPROVED** [review]
👌

**Pull request merged**
