### PR TITLE
a framework for expected conditions in pure javascript

### PR DESCRIPTION
**Pull request by pbruski**

### CODE REVIEW

**Comment by pbruski** [comment]
Come to think of it, maybe putting it into separate library would be better.

**Comment by dagguh** [comment]
> Come to think of it, maybe putting it into separate library would be better.

It's fine to incubate it here and when battle-tested extract outside.

**Comment by pbruski** [comment]
Yeah, but I realised I want these in jira-software-actions too (for ViewBoardPage.waitForBoard and ViewBacklogPage.waitForBacklog). Also, this is something Confluence might be interested in too. 
I'll just make sure it's green with the jira-actions and extract it.

**Comment by pbruski** [comment]
Closed in favour of https://github.com/atlassian/jira-actions/pull/38

**Pull request closed without merging**
